name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Check
        run: vp check

      - name: Test
        run: vp test

      - name: Pack
        run: vp pack
